version: '3.7'

services:
  chi-todo:
    container_name: chi-todo
    image: chi-todo:1.3.1
    ports:
      - 9000:9000
    environment:
      - API_URL=:9000
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=
      - MYSQL_HOST=host.docker.internal
      - MYSQL_PORT=3306
      - MYSQL_DBNAME=todo